---
# versions 
argocd_version: "v3.5.1"
k3s_version: "v1.36.3+k3s1"

# other variables
argocd_fqdn: argocd.jook.network
extra_server_args_list:
   - ""
home_dir: "{{ lookup('env','HOME') }}"
k3s_fqdn: kubernetes.jook.network
