---
# get k3s installed version
- name: get k3s installed version
  ansible.builtin.shell: "k3s --version 2>/dev/null || echo ''"
  register: k3s_version_output
  changed_when: false

# set k3s installed version
- name: set k3s installed version
  ansible.builtin.set_fact:
    k3s_installed_version: "{{ k3s_version_output.stdout.split(' ')[2] | default('v0.0.0') }}"

# download and install k3s
- name: download and install k3s
  when: k3s_installed_version is version(k3s_version, '<')
  block:
    - name: download k3s
      ansible.builtin.get_url:
        url: https://get.k3s.io/
        timeout: 120
        dest: /usr/local/bin/k3s-install.sh
        owner: root
        group: root
        mode: "0755"

    - name: install k3s
      ansible.builtin.command: /usr/local/bin/k3s-install.sh
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
        INSTALL_K3S_EXEC: "{{ extra_server_args_list | join (' ') }} --tls-san={{ k3s_fqdn }}"

# create ~/.kube
- name: create ~/.kube
  ansible.builtin.file:
    path: "{{ home_dir }}/.kube"
    state: directory
    mode: '0700'
  become: false
  delegate_to: localhost

# get kubeconfig
- name: get kubeconfig
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ home_dir }}/.kube/config"
    flat: true

# set server address in kubeconfig
- name: set server address in kubeconfig
  replace:
    path: "{{ home_dir }}/.kube/config"
    regexp: '127.0.0.1'
    replace: "{{ k3s_fqdn }}"
  delegate_to: localhost