---
- name: prerequisites
  include_tasks: prerequisites.yaml

- name: k3s
  include_tasks: k3s.yaml

- name: metallb
  include_tasks: metallb.yaml

- name: cert-manager
  include_tasks: cert-manager.yaml

- name: argocd
  include_tasks: argocd.yaml