---
# disable swap in current session
- name: disable swap in current session
  ansible.builtin.command: swapoff -a
  become: true
  changed_when: true
  when: ansible_swaptotal_mb > 0

# disable swap in /etc/fstab
- name: disable swap in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#].*\bswap\b.*)$'
    replace: '\1# \2'